### ISSUE TITLE
TypeError: this.charAt is not a function / vue-tables-1.6.40

### ISSUE THREAD

**Issue by m-behr** [matfish2/vue-tables#124]
Hi,
getting this error after upgrading vue-tables, using server-side tables.
I am not sure, if it is relevant but ending up in module.exports (from Chrome Sources-View)
```javascript
},{}],30:[function(require,module,exports){
module.exports = function() {
    return this.charAt(0).toUpperCase() + this.slice(1);
}
```
'this ' points to 'window'

if you need further informations, please let me know.

Greetings
Michael

- Vue.js version: v1.0.28
- consumed using: (browserify)
- FULL error message (including stack trace):
```
users-f58d1eacdd.js:994 TypeError: this.charAt is not a function
    at module.exports (http://localhost:8000/build/js/admin/users-f58d1eacdd.js:2659:17)
    at Array.params.add (http://localhost:8000/build/js/admin/users-f58d1eacdd.js:1407:21)
    at Function.<anonymous> (http://localhost:8000/build/js/admin/users-f58d1eacdd.js:1474:20)
    at each (http://localhost:8000/build/js/admin/users-f58d1eacdd.js:1077:26)
    at serialize (http://localhost:8000/build/js/admin/users-f58d1eacdd.js:1461:5)
    at Object.<anonymous> (http://localhost:8000/build/js/admin/users-f58d1eacdd.js:1472:13)
    at each (http://localhost:8000/build/js/admin/users-f58d1eacdd.js:1077:26)
    at serialize (http://localhost:8000/build/js/admin/users-f58d1eacdd.js:1461:5)
    at Function.Url.params (http://localhost:8000/build/js/admin/users-f58d1eacdd.js:1417:5)
    at query (http://localhost:8000/build/js/admin/users-f58d1eacdd.js:1172:17)
```
- relevant code:
```javascript
/**
 * Query Parameter Transform.
 */

function query (options, next) {

    var urlParams = Object.keys(Url.options.params),
        query = {},
        url = next(options);

    each(options.params, function (value, key) {
        if (urlParams.indexOf(key) === -1) {
            query[key] = value;
        }
    });

    query = Url.params(query); // Error starts here

    if (query) {
        url += (url.indexOf('?') == -1 ? '?' : '&') + query;
    }

    return url;
}
```

**Comment by matfish2** [comment]
I need more context. Where do you use this `query` function? How is it bound to the plugin's life cycle?
The error stems from the `ucfirst` method, which is used only once to create the default heading, in case none was provided. (see `get-headings.js`). `this` should be a string, so I'm guessing it might have to do with scoping issues, arising from usage of ES6. Please provide a fuller picture.

**Comment by m-behr** [comment]
The query function was added via last commit
https://github.com/matfish2/vue-tables/commit/5a78e96b151f59ba257ba491b9c3c51bd2e4b9d1

if i rollback these changes, it works again

**Comment by erikwestlund** [comment]
I face the same issue.  I'm using Webpack w/ Laravel Elixir 6.

Like @m-behr, when I roll back to version 1.6.36, these issues go away. 

Here's my console output:

```
vue-resource.common.js?2f13:280 TypeError: this.charAt is not a function(…)error @ vue-resource.common.js?2f13:280(anonymous function) @ vue-resource.common.js?2f13:1356
set-data.js?2bab:2 Uncaught (in promise) TypeError: Cannot read property 'data' of undefined(…)module.exports @ set-data.js?2bab:2(anonymous function) @ vue.common.js?e881:216(anonymous function) @ get-data.js?1fcc:26
vue-resource.common.js?2f13:280 TypeError: this.charAt is not a function(…)error @ vue-resource.common.js?2f13:280(anonymous function) @ vue-resource.common.js?2f13:1356
set-data.js?2bab:2 Uncaught (in promise) TypeError: Cannot read property 'data' of undefined(…)module.exports @ set-data.js?2bab:2(anonymous function) @ vue.common.js?e881:216(anonymous function) @ get-data.js?1fcc:26
```

**Comment by matfish2** [comment]
@m-behr, thanks for your input. The function was designed for a query object, which is sent along when filterByColumn is set to true. I forgot to factor in the normal string filter.
