### ISSUE TITLE
Pagination issue

### ISSUE THREAD

**Issue by lavezzi1** [matfish2/vue-tables#60]
- Vue.js version: 1.25
- consumed using: (browserify/webpack/pre-compiled) webpack
- FULL error message (including stack trace):
```
ERROR in ./~/vue-tables/lib/table-template.html
Module parse failed: /code/test/starter/node_modules/vue-tables/lib/table-template.html Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:0)
    at Parser.pp.raise (/code/test/starter/node_modules/acorn/dist/acorn.js:923:13)
    at Parser.pp.unexpected (/code/test/starter/node_modules/acorn/dist/acorn.js:1490:8)
    at Parser.pp.parseExprAtom (/code/test/starter/node_modules/acorn/dist/acorn.js:333:12)
    at Parser.pp.parseExprSubscripts (/code/test/starter/node_modules/acorn/dist/acorn.js:228:19)
    at Parser.pp.parseMaybeUnary (/code/test/starter/node_modules/acorn/dist/acorn.js:207:17)
    at Parser.pp.parseExprOps (/code/test/starter/node_modules/acorn/dist/acorn.js:154:19)
    at Parser.pp.parseMaybeConditional (/code/test/starter/node_modules/acorn/dist/acorn.js:136:19)
    at Parser.pp.parseMaybeAssign (/code/test/starter/node_modules/acorn/dist/acorn.js:112:19)
    at Parser.pp.parseExpression (/code/test/starter/node_modules/acorn/dist/acorn.js:88:19)
    at Parser.pp.parseStatement (/code/test/starter/node_modules/acorn/dist/acorn.js:1771:23)
    at Parser.pp.parseTopLevel (/code/test/starter/node_modules/acorn/dist/acorn.js:1666:21)
    at Parser.parse (/code/test/starter/node_modules/acorn/dist/acorn.js:1632:17)
    at Object.parse (/code/test/starter/node_modules/acorn/dist/acorn.js:885:44)
    at Parser.parse (/code/test/starter/node_modules/webpack/lib/Parser.js:902:15)
    at DependenciesBlock.<anonymous> (/code/test/starter/node_modules/webpack/lib/NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (/code/test/starter/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
 @ ./~/vue-tables/lib/helpers/generate-table-html.js 3:17-50

ERROR in ./~/v-pagination/src/template.html
Module parse failed: /code/test/starter/node_modules/v-pagination/src/template.html Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:0)
    at Parser.pp.raise (/code/test/starter/node_modules/acorn/dist/acorn.js:923:13)
    at Parser.pp.unexpected (/code/test/starter/node_modules/acorn/dist/acorn.js:1490:8)
    at Parser.pp.parseExprAtom (/code/test/starter/node_modules/acorn/dist/acorn.js:333:12)
    at Parser.pp.parseExprSubscripts (/code/test/starter/node_modules/acorn/dist/acorn.js:228:19)
    at Parser.pp.parseMaybeUnary (/code/test/starter/node_modules/acorn/dist/acorn.js:207:17)
    at Parser.pp.parseExprOps (/code/test/starter/node_modules/acorn/dist/acorn.js:154:19)
    at Parser.pp.parseMaybeConditional (/code/test/starter/node_modules/acorn/dist/acorn.js:136:19)
    at Parser.pp.parseMaybeAssign (/code/test/starter/node_modules/acorn/dist/acorn.js:112:19)
    at Parser.pp.parseExpression (/code/test/starter/node_modules/acorn/dist/acorn.js:88:19)
    at Parser.pp.parseStatement (/code/test/starter/node_modules/acorn/dist/acorn.js:1771:23)
    at Parser.pp.parseTopLevel (/code/test/starter/node_modules/acorn/dist/acorn.js:1666:21)
    at Parser.parse (/code/test/starter/node_modules/acorn/dist/acorn.js:1632:17)
    at Object.parse (/code/test/starter/node_modules/acorn/dist/acorn.js:885:44)
    at Parser.parse (/code/test/starter/node_modules/webpack/lib/Parser.js:902:15)
    at DependenciesBlock.<anonymous> (/code/test/starter/node_modules/webpack/lib/NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (/code/test/starter/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
 @ ./~/v-pagination/index.js 4:12-42
```
- relevant code:
- steps for reproducing the issue:

How to fix it?

**Comment by matfish2** [comment]
You must include the `html-loader`. See issue #23.
